In [13]:
# Importing the required libraries
import requests
import pandas as pd
from bs4 import BeautifulSoup
import pandas as pd

In [14]:
# Downloading contents of the web page
url = "https://www.census.gov/geographies/reference-files/2010/geo/state-area.html"
data = requests.get(url).text

# Creating BeautifulSoup object
soup = BeautifulSoup(data, 'html.parser')

In [15]:
# Creating list with all tables
table = soup.find('table')

In [16]:
# Defining of the dataframe
df = pd.DataFrame(columns=['sub_region_1', 'Total_Area'])

# Collecting Ddata
for row in table.tbody.find_all('tr'):    
    # Find all data for each column
    columns = row.find_all('td')
    
    if(columns != []):
        state = columns[0].text.strip()
        total_area = columns[2].text.strip()

        df = df.append({'sub_region_1': state, 'Total_Area': total_area}, ignore_index=True)

df = df.drop([0,1,2])

In [17]:
# State name mapping table
state_mapping_table = pd.read_csv('../Input_datasets/Mobility_flow_prediction_shared/us_states_w_fips_and_coordinates.csv')

In [18]:
df = pd.merge(df, state_mapping_table[['sub_region_1', 'FIPS']], on='sub_region_1')

In [19]:
df.to_csv("../Input_datasets/Mobility_flow_prediction_shared/US_state_sizes.csv")

In [20]:
df

            sub_region_1 Total_Area  FIPS
0                Alabama    135,767     1
1                 Alaska  1,723,337     2
2                Arizona    295,234     4
3               Arkansas    137,732     5
4             California    423,967     6
5               Colorado    269,601     8
6            Connecticut     14,357     9
7               Delaware      6,446    10
8   District of Columbia        177    11
9                Florida    170,312    12
10               Georgia    153,910    13
11                Hawaii     28,313    15
12                 Idaho    216,443    16
13              Illinois    149,995    17
14               Indiana     94,326    18
15                  Iowa    145,746    19
16                Kansas    213,100    20
17              Kentucky    104,656    21
18             Louisiana    135,659    22
19                 Maine     91,633    23
20              Maryland     32,131    24
21         Massachusetts     27,336    25
22              Michigan    250,487    26
23             Minnesota    225,163    27
24           Mississippi    125,438    28
25              Missouri    180,540    29
26               Montana    380,831    30
27              Nebraska    200,330    31
28                Nevada    286,380    32
29         New Hampshire     24,214    33
30            New Jersey     22,591    34
31            New Mexico    314,917    35
32              New York    141,297    36
33        North Carolina    139,391    37
34          North Dakota    183,108    38
35                  Ohio    116,098    39
36              Oklahoma    181,037    40
37                Oregon    254,799    41
38          Pennsylvania    119,280    42
39          Rhode Island      4,001    44
40        South Carolina     82,933    45
41          South Dakota    199,729    46
42             Tennessee    109,153    47
43                 Texas    695,662    48
44                  Utah    219,882    49
45               Vermont     24,906    50
46              Virginia    110,787    51
47            Washington    184,661    53
48         West Virginia     62,756    54
49             Wisconsin    169,635    55
50               Wyoming    253,335    56